# -*- coding: utf-8 -*-
"""IA_Actividad2_Laura E. Mtz Hdz_1841866

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zP2ke4QYxuc7qQ_4RwgoiSPeN9wJ9qw8

**Actividad 2.-** Ejercicios Introducción Python

**Nombre:** Laura Elizabeth Martínez Hernández

**Matrícula**: 1841866 **Hora clase:** N4N5N6

# **Ejercicio 1:**

Crear un programa que pregunte al usuario por su nombre, edad, una frase favorita y autor de la frase favorita. El programa deberá de imprimir un mensaje compuesto por el nombre y edad del usuario diciendo que su frase favorita es la que dió anteriormente y el autor de dicha frase es el nombre previamente dado. 

---
"""

#aqui le pido al usuario que conteste unas preguntas
nombre= input("¿Cuál es tu nombre?  ")
edad= input("¿Cuántos años tienes?  ") #numero (sin la palabra años)
frase= input("¿Cuál es tu frase favorita?  ")
autor= input ("¿Quién es el autor de la frase?  ")

print(f"Mi nombre es {nombre}, tengo {edad} años y mi frase favorita es {frase}, su autor es {autor}. ")

"""# **Ejercicio 2:**

Crear un programa que le pida al usuario capturar dos números enteros y dos números flotantes. Después, realizará la suma, resta, multiplicación y división, de ambos pares de números. Como resultado se deberán de obtener 8 valores. Imprimir todos estos resultados.

---
"""

x= int(input("Digite un número entero: ")) #numero entero 1
y= int(input("Digite otro número entero: ")) #numero entero 2
m= float(input("Digite un número con decimal(es): ")) #numero decimal 1
n= float(input("Digite otro número con decimal(es): ")) #numero decimal 2

sumaInt= x+y
restaInt= x-y
multInt= x*y
divInt= x/y
print(f"Los números enteros elegidos fueron {x} y {y}. La suma de {x}+{y} es {sumaInt}, la resta de {x}-{y} es {restaInt}, la multiplicación de ({x})({y}) es {multInt} y la división de {x}/{y} es {divInt} ")

sumaf= m+n
restaf= m-n
multf= m*n
divf=m/n
print(f"Los números decimales elegidos fueron {m} y {n}. La suma de {m}+{n} es {sumaf}, la resta de {m}-{n} es {restaf}, la multiplicación de ({m})({n}) es {multf} y la división de {m}/{n} es {divf} ")

"""# **Ejercicio 3:**

Crear un programa que evalúe dos expresiones lógicas con `and`, dos con `or` y dos con `not`. Cada expresión deberá hacer uso de operadores de comparación. 

---
"""

#comparacion con and
w= float(input("Digite un número:  ")) #le pido al usuario que me de un numero entero o decimal
print(1<w and 20>w)
print(80<=w and 17!=w)

#comparacion con or
j= float(input("Digite un número:  ")) #le pido al usuario que me de un numero entero o decimal
print(7<j or 40>j)
print(-2<j or 13>j)

#comparacion con not
s=float(input("Digite un número:  ")) #le pido al usuario que me de un numero entero o decimal
print(not 33>=s)
print(not 14==s)